window.jQuery = window.$ = require('../../../node_modules/jquery/dist/jquery');
import { cyan } from '../../../mods/cyan/Cyan.es6';
import '../../../node_modules/angular/angular';
import '../../../node_modules/angular-cookies/angular-cookies';
import '../../../node_modules/angular-resource/angular-resource';
import '../../../node_modules/angular-bootstrap/ui-bootstrap-tpls';
import '../../../node_modules/angular-ui-router/release/angular-ui-router';
import '../../../node_modules/angular-animate/angular-animate';
import '../../../node_modules/angular-touch/angular-touch';
import '../../../node_modules/oclazyload/dist/ocLazyLoad';
window.cyan = cyan;
